Repository I-JUNNYLAND-I/algorithm, pull requests merged in 2022-12, with the labels that each got.

#30 day 3
  0020-valid-parentheses/0020-valid-parentheses.java
  0020-valid-parentheses/0020-valid-parentheses.kt
  0020-valid-parentheses/NOTES.md
  0020-valid-parentheses/README.md
  0175-combine-two-tables/0175-combine-two-tables.sql
  0175-combine-two-tables/NOTES.md
  0175-combine-two-tables/README.md
  0434-number-of-segments-in-a-string/0434-number-of-segments-in-a-string.kt
  0434-number-of-segments-in-a-string/NOTES.md
  0434-number-of-segments-in-a-string/README.md
  0709-to-lower-case/0709-to-lower-case.kt
  0709-to-lower-case/NOTES.md
  0709-to-lower-case/README.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/1050-actors-and-directors-who-cooperated-at-least-three-times.sql
  1050-actors-and-directors-who-cooperated-at-least-three-times/NOTES.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/README.md
  1360-number-of-days-between-two-dates/1360-number-of-days-between-two-dates.kt
  1360-number-of-days-between-two-dates/NOTES.md
  1360-number-of-days-between-two-dates/README.md
  2185-counting-words-with-a-given-prefix/2185-counting-words-with-a-given-prefix.kt
  2185-counting-words-with-a-given-prefix/NOTES.md
  2185-counting-words-with-a-given-prefix/README.md
  2418-sort-the-people/2418-sort-the-people.kt
  2418-sort-the-people/NOTES.md
  2418-sort-the-people/README.md
Labels: 🎉 All pass

#31 day 3
  0020-valid-parentheses/0020-valid-parentheses.py
  0020-valid-parentheses/NOTES.md
  0020-valid-parentheses/README.md
  0175-combine-two-tables/0175-combine-two-tables.sql
  0175-combine-two-tables/NOTES.md
  0175-combine-two-tables/README.md
  2185-counting-words-with-a-given-prefix/2185-counting-words-with-a-given-prefix.py
  2185-counting-words-with-a-given-prefix/NOTES.md
  2185-counting-words-with-a-given-prefix/README.md
  2418-sort-the-people/2418-sort-the-people.py
  2418-sort-the-people/NOTES.md
  2418-sort-the-people/README.md
Labels: 🎉 All pass

#32 day 3
  0020-valid-parentheses/0020-valid-parentheses.java
  0020-valid-parentheses/NOTES.md
  0020-valid-parentheses/README.md
  0175-combine-two-tables/0175-combine-two-tables.sql
  0175-combine-two-tables/NOTES.md
  0175-combine-two-tables/README.md
  2185-counting-words-with-a-given-prefix/2185-counting-words-with-a-given-prefix.java
  2185-counting-words-with-a-given-prefix/NOTES.md
  2185-counting-words-with-a-given-prefix/README.md
  2418-sort-the-people/2418-sort-the-people.java
  2418-sort-the-people/NOTES.md
  2418-sort-the-people/README.md
Labels: 🎉 All pass

#35 Day 3
  0020-valid-parentheses/0020-valid-parentheses.java
  0020-valid-parentheses/NOTES.md
  0020-valid-parentheses/README.md
  0175-combine-two-tables/0175-combine-two-tables.sql
  0175-combine-two-tables/NOTES.md
  0175-combine-two-tables/README.md
  1704-determine-if-string-halves-are-alike/1704-determine-if-string-halves-are-alike.java
  1704-determine-if-string-halves-are-alike/NOTES.md
  1704-determine-if-string-halves-are-alike/README.md
  2185-counting-words-with-a-given-prefix/2185-counting-words-with-a-given-prefix.java
  2185-counting-words-with-a-given-prefix/NOTES.md
  2185-counting-words-with-a-given-prefix/README.md
  2418-sort-the-people/2418-sort-the-people.java
  2418-sort-the-people/NOTES.md
  2418-sort-the-people/README.md
Labels: 🎉 All pass

#37 day 3
  .github/ISSUE_TEMPLATE/custom.yaml
  0020-valid-parentheses/0020-valid-parentheses.java
  0020-valid-parentheses/NOTES.md
Labels: 🎉 All pass

#39 day 4
  0434-number-of-segments-in-a-string/0434-number-of-segments-in-a-string.py
  0434-number-of-segments-in-a-string/NOTES.md
  0434-number-of-segments-in-a-string/README.md
  0709-to-lower-case/0709-to-lower-case.py
  0709-to-lower-case/NOTES.md
  0709-to-lower-case/README.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/1050-actors-and-directors-who-cooperated-at-least-three-times.sql
  1050-actors-and-directors-who-cooperated-at-least-three-times/NOTES.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/README.md
  1360-number-of-days-between-two-dates/1360-number-of-days-between-two-dates.py
  1360-number-of-days-between-two-dates/NOTES.md
  1360-number-of-days-between-two-dates/README.md
Labels: 🎉 All pass

#40 Day 4
  0434-number-of-segments-in-a-string/0434-number-of-segments-in-a-string.java
  0434-number-of-segments-in-a-string/NOTES.md
  0434-number-of-segments-in-a-string/README.md
  0709-to-lower-case/NOTES.md
  0709-to-lower-case/README.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/1050-actors-and-directors-who-cooperated-at-least-three-times.sql
  1050-actors-and-directors-who-cooperated-at-least-three-times/NOTES.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/README.md
  1360-number-of-days-between-two-dates/1360-number-of-days-between-two-dates.java
  1360-number-of-days-between-two-dates/NOTES.md
  1360-number-of-days-between-two-dates/README.md
Labels: 🎉 All pass

#41 DAY 3 & 4
  0020-valid-parentheses/0020-valid-parentheses.java
  0020-valid-parentheses/NOTES.md
  0020-valid-parentheses/README.md
  0175-combine-two-tables/0175-combine-two-tables.sql
  0175-combine-two-tables/NOTES.md
  0175-combine-two-tables/README.md
  0434-number-of-segments-in-a-string/0434-number-of-segments-in-a-string.java
  0434-number-of-segments-in-a-string/NOTES.md
  0434-number-of-segments-in-a-string/README.md
  0709-to-lower-case/0709-to-lower-case.java
  0709-to-lower-case/NOTES.md
  0709-to-lower-case/README.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/1050-actors-and-directors-who-cooperated-at-least-three-times.sql
  1050-actors-and-directors-who-cooperated-at-least-three-times/NOTES.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/README.md
  1360-number-of-days-between-two-dates/1360-number-of-days-between-two-dates.java
  1360-number-of-days-between-two-dates/NOTES.md
  1360-number-of-days-between-two-dates/README.md
  2185-counting-words-with-a-given-prefix/2185-counting-words-with-a-given-prefix.java
  2185-counting-words-with-a-given-prefix/NOTES.md
  2185-counting-words-with-a-given-prefix/README.md
  2418-sort-the-people/2418-sort-the-people.java
  2418-sort-the-people/NOTES.md
  2418-sort-the-people/README.md
Labels: 🎉 All pass

#42 Day 4
  0434-number-of-segments-in-a-string/0434-number-of-segments-in-a-string.java
  0434-number-of-segments-in-a-string/NOTES.md
  0434-number-of-segments-in-a-string/README.md
  0709-to-lower-case/0709-to-lower-case.java
  0709-to-lower-case/NOTES.md
  0709-to-lower-case/README.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/1050-actors-and-directors-who-cooperated-at-least-three-times.sql
  1050-actors-and-directors-who-cooperated-at-least-three-times/NOTES.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/README.md
  1360-number-of-days-between-two-dates/1360-number-of-days-between-two-dates.java
  1360-number-of-days-between-two-dates/NOTES.md
  1360-number-of-days-between-two-dates/README.md
Labels: 🎉 All pass

#43 day 4
  0434-number-of-segments-in-a-string/0434-number-of-segments-in-a-string.java
  0434-number-of-segments-in-a-string/NOTES.md
  0434-number-of-segments-in-a-string/README.md
  0709-to-lower-case/0709-to-lower-case.java
  0709-to-lower-case/NOTES.md
  0709-to-lower-case/README.md
  1050-actors-and-directors-who-cooperated-at-least-three-times/1050-actors-and-directors-who-cooperated-at-least-three-times.sql
  1050-actors-and-directors-who-cooperated-at-least-three-times/NOTES.md
  1360-number-of-days-between-two-dates/1360-number-of-days-between-two-dates.java
  1360-number-of-days-between-two-dates/NOTES.md
  1360-number-of-days-between-two-dates/README.md
Labels: 🎉 All pass

#48 Day5
  0231-power-of-two/NOTES.md
  0231-power-of-two/README.md
  0258-add-digits/0258-add-digits.java
  0258-add-digits/NOTES.md
  0258-add-digits/README.md
  0283-move-zeroes/0283-move-zeroes.java
  0283-move-zeroes/NOTES.md
  0283-move-zeroes/README.md
  1084-sales-analysis-iii/1084-sales-analysis-iii.sql
  1084-sales-analysis-iii/NOTES.md
  1084-sales-analysis-iii/README.md
Labels: 🎉 All pass

#47 Day 5
  0176-second-highest-salary/NOTES.md
  0176-second-highest-salary/README.md
  0231-power-of-two/0231-power-of-two.java
  0231-power-of-two/NOTES.md
  0231-power-of-two/README.md
  0258-add-digits/0258-add-digits.java
  0258-add-digits/NOTES.md
  0258-add-digits/README.md
  0283-move-zeroes/0283-move-zeroes.java
  0283-move-zeroes/0283-move-zeroes.py
  0283-move-zeroes/NOTES.md
  0283-move-zeroes/README.md
  0451-sort-characters-by-frequency/0451-sort-characters-by-frequency.java
  0451-sort-characters-by-frequency/NOTES.md
  0451-sort-characters-by-frequency/README.md
  1084-sales-analysis-iii/1084-sales-analysis-iii.sql
  1084-sales-analysis-iii/NOTES.md
  1084-sales-analysis-iii/README.md
  1657-determine-if-two-strings-are-close/1657-determine-if-two-strings-are-close.java
  1657-determine-if-two-strings-are-close/NOTES.md
  1657-determine-if-two-strings-are-close/README.md
Labels: 🎉 All pass

#46 day 5
  0231-power-of-two/0231-power-of-two.py
  0231-power-of-two/NOTES.md
  0231-power-of-two/README.md
  0258-add-digits/NOTES.md
  0258-add-digits/README.md
  0283-move-zeroes/0283-move-zeroes.py
  0283-move-zeroes/NOTES.md
  0283-move-zeroes/README.md
  1084-sales-analysis-iii/1084-sales-analysis-iii.sql
  1084-sales-analysis-iii/NOTES.md
  1084-sales-analysis-iii/README.md
Labels: 🎉 All pass

#45 day 5
  0231-power-of-two/0231-power-of-two.kt
  0231-power-of-two/NOTES.md
  0231-power-of-two/README.md
  0258-add-digits/0258-add-digits.kt
  0258-add-digits/NOTES.md
  0258-add-digits/README.md
  0283-move-zeroes/0283-move-zeroes.kt
  0283-move-zeroes/NOTES.md
  0283-move-zeroes/README.md
Labels: 🎉 All pass

#49 Day 5
  0231-power-of-two/0231-power-of-two.java
  0231-power-of-two/NOTES.md
  0231-power-of-two/README.md
  0258-add-digits/0258-add-digits.java
  0258-add-digits/NOTES.md
  0258-add-digits/README.md
  0283-move-zeroes/0283-move-zeroes.java
  0283-move-zeroes/NOTES.md
  0283-move-zeroes/README.md
  1084-sales-analysis-iii/1084-sales-analysis-iii.sql
  1084-sales-analysis-iii/NOTES.md
  1084-sales-analysis-iii/README.md
Labels: 🎉 All pass

#53 Day 6 & Day7
  0890-find-and-replace-pattern/0890-find-and-replace-pattern.java
  0890-find-and-replace-pattern/NOTES.md
  0890-find-and-replace-pattern/README.md
  1108-defanging-an-ip-address/1108-defanging-an-ip-address.java
  1108-defanging-an-ip-address/NOTES.md
  1108-defanging-an-ip-address/README.md
  1179-reformat-department-table/1179-reformat-department-table.sql
  1179-reformat-department-table/NOTES.md
  1179-reformat-department-table/README.md
  1741-find-total-time-spent-by-each-employee/1741-find-total-time-spent-by-each-employee.sql
  1741-find-total-time-spent-by-each-employee/NOTES.md
  1768-merge-strings-alternately/1768-merge-strings-alternately.java
  1768-merge-strings-alternately/NOTES.md
  1768-merge-strings-alternately/README.md
  1859-sorting-the-sentence/1859-sorting-the-sentence.java
  1859-sorting-the-sentence/NOTES.md
  1859-sorting-the-sentence/README.md
  1876-substrings-of-size-three-with-distinct-characters/1876-substrings-of-size-three-with-distinct-characters.java
  1876-substrings-of-size-three-with-distinct-characters/NOTES.md
  1876-substrings-of-size-three-with-distinct-characters/README.md
  2255-count-prefixes-of-a-given-string/NOTES.md
  2255-count-prefixes-of-a-given-string/README.md
  2256-minimum-average-difference/2256-minimum-average-difference.java
  2256-minimum-average-difference/NOTES.md
  2256-minimum-average-difference/README.md
  2490-circular-sentence/2490-circular-sentence.java
  2490-circular-sentence/NOTES.md
  2490-circular-sentence/README.md
Labels: 🎉 All pass

#51 day 6
  0890-find-and-replace-pattern/0890-find-and-replace-pattern.java
  0890-find-and-replace-pattern/0890-find-and-replace-pattern.kt
  0890-find-and-replace-pattern/NOTES.md
  0890-find-and-replace-pattern/README.md
  1108-defanging-an-ip-address/1108-defanging-an-ip-address.kt
  1108-defanging-an-ip-address/NOTES.md
  1108-defanging-an-ip-address/README.md
  1179-reformat-department-table/1179-reformat-department-table.sql
  1179-reformat-department-table/NOTES.md
  1179-reformat-department-table/README.md
  1741-find-total-time-spent-by-each-employee/1741-find-total-time-spent-by-each-employee.sql
  1741-find-total-time-spent-by-each-employee/NOTES.md
  1741-find-total-time-spent-by-each-employee/README.md
  1768-merge-strings-alternately/1768-merge-strings-alternately.kt
  1768-merge-strings-alternately/NOTES.md
  1768-merge-strings-alternately/README.md
  1859-sorting-the-sentence/1859-sorting-the-sentence.kt
  1859-sorting-the-sentence/NOTES.md
  1859-sorting-the-sentence/README.md
  1876-substrings-of-size-three-with-distinct-characters/1876-substrings-of-size-three-with-distinct-characters.kt
  1876-substrings-of-size-three-with-distinct-characters/NOTES.md
  1876-substrings-of-size-three-with-distinct-characters/README.md
  2255-count-prefixes-of-a-given-string/2255-count-prefixes-of-a-given-string.kt
  2255-count-prefixes-of-a-given-string/NOTES.md
  2255-count-prefixes-of-a-given-string/README.md
Labels: 🎉 All pass

#58 Day 5 & 6 & 7 & 8
  0231-power-of-two/0231-power-of-two.java
  0231-power-of-two/NOTES.md
  0231-power-of-two/README.md
  0258-add-digits/0258-add-digits.java
  0258-add-digits/NOTES.md
  0258-add-digits/README.md
  0283-move-zeroes/0283-move-zeroes.java
  0283-move-zeroes/NOTES.md
  0283-move-zeroes/README.md
  1108-defanging-an-ip-address/1108-defanging-an-ip-address.java
  1108-defanging-an-ip-address/NOTES.md
  1108-defanging-an-ip-address/README.md
  1179-reformat-department-table/1179-reformat-department-table.sql
  1179-reformat-department-table/NOTES.md
  1179-reformat-department-table/README.md
  1587-bank-account-summary-ii/1587-bank-account-summary-ii.sql
  1587-bank-account-summary-ii/NOTES.md
  1587-bank-account-summary-ii/README.md
  1741-find-total-time-spent-by-each-employee/1741-find-total-time-spent-by-each-employee.sql
  1741-find-total-time-spent-by-each-employee/NOTES.md
  1741-find-total-time-spent-by-each-employee/README.md
  1768-merge-strings-alternately/1768-merge-strings-alternately.java
  1768-merge-strings-alternately/NOTES.md
  1768-merge-strings-alternately/README.md
  1859-sorting-the-sentence/1859-sorting-the-sentence.java
  1859-sorting-the-sentence/NOTES.md
  1859-sorting-the-sentence/README.md
  1876-substrings-of-size-three-with-distinct-characters/1876-substrings-of-size-three-with-distinct-characters.java
  1876-substrings-of-size-three-with-distinct-characters/NOTES.md
  1876-substrings-of-size-three-with-distinct-characters/README.md
  1920-build-array-from-permutation/1920-build-array-from-permutation.java
  1920-build-array-from-permutation/NOTES.md
  1920-build-array-from-permutation/README.md
  1929-concatenation-of-array/1929-concatenation-of-array.java
  1929-concatenation-of-array/NOTES.md
  1929-concatenation-of-array/README.md
  2011-final-value-of-variable-after-performing-operations/NOTES.md
  2011-final-value-of-variable-after-performing-operations/README.md
  2255-count-prefixes-of-a-given-string/NOTES.md
  2255-count-prefixes-of-a-given-string/README.md
Labels: 🎉 All pass

#60 Day 6 & 7 & 8
  0890-find-and-replace-pattern/0890-find-and-replace-pattern.py
  0890-find-and-replace-pattern/NOTES.md
  0890-find-and-replace-pattern/README.md
  1108-defanging-an-ip-address/1108-defanging-an-ip-address.py
  1108-defanging-an-ip-address/NOTES.md
  1108-defanging-an-ip-address/README.md
  1179-reformat-department-table/1179-reformat-department-table.sql
  1179-reformat-department-table/NOTES.md
  1179-reformat-department-table/README.md
  1587-bank-account-summary-ii/1587-bank-account-summary-ii.sql
  1587-bank-account-summary-ii/NOTES.md
  1587-bank-account-summary-ii/README.md
  1741-find-total-time-spent-by-each-employee/1741-find-total-time-spent-by-each-employee.sql
  1741-find-total-time-spent-by-each-employee/NOTES.md
  1741-find-total-time-spent-by-each-employee/README.md
  1768-merge-strings-alternately/NOTES.md
  1768-merge-strings-alternately/README.md
  1859-sorting-the-sentence/NOTES.md
  1859-sorting-the-sentence/README.md
  1876-substrings-of-size-three-with-distinct-characters/1876-substrings-of-size-three-with-distinct-characters.py
  1876-substrings-of-size-three-with-distinct-characters/NOTES.md
  1876-substrings-of-size-three-with-distinct-characters/README.md
  1920-build-array-from-permutation/1920-build-array-from-permutation.py
  1920-build-array-from-permutation/NOTES.md
  1920-build-array-from-permutation/README.md
  1929-concatenation-of-array/1929-concatenation-of-array.py
  1929-concatenation-of-array/NOTES.md
  1929-concatenation-of-array/README.md
  2011-final-value-of-variable-after-performing-operations/2011-final-value-of-variable-after-performing-operations.py
  2011-final-value-of-variable-after-performing-operations/NOTES.md
  2011-final-value-of-variable-after-performing-operations/README.md
  2255-count-prefixes-of-a-given-string/2255-count-prefixes-of-a-given-string.py
  2255-count-prefixes-of-a-given-string/NOTES.md
  2255-count-prefixes-of-a-given-string/README.md
Labels: 🎉 All pass

#59 Day 8
  0876-middle-of-the-linked-list/0876-middle-of-the-linked-list.java
  0876-middle-of-the-linked-list/NOTES.md
  0876-middle-of-the-linked-list/README.md
  1587-bank-account-summary-ii/1587-bank-account-summary-ii.sql
  1587-bank-account-summary-ii/NOTES.md
  1587-bank-account-summary-ii/README.md
  1920-build-array-from-permutation/1920-build-array-from-permutation.java
  1920-build-array-from-permutation/NOTES.md
  1920-build-array-from-permutation/README.md
  1929-concatenation-of-array/1929-concatenation-of-array.java
  1929-concatenation-of-array/NOTES.md
  1929-concatenation-of-array/README.md
  2011-final-value-of-variable-after-performing-operations/2011-final-value-of-variable-after-performing-operations.java
  2011-final-value-of-variable-after-performing-operations/NOTES.md
  2011-final-value-of-variable-after-performing-operations/README.md
Labels: 🎉 All pass

#57 day 8
  1587-bank-account-summary-ii/1587-bank-account-summary-ii.sql
  1587-bank-account-summary-ii/NOTES.md
  1587-bank-account-summary-ii/README.md
  1920-build-array-from-permutation/1920-build-array-from-permutation.kt
  1920-build-array-from-permutation/NOTES.md
  1920-build-array-from-permutation/README.md
  1929-concatenation-of-array/1929-concatenation-of-array.kt
  1929-concatenation-of-array/NOTES.md
  1929-concatenation-of-array/README.md
  2011-final-value-of-variable-after-performing-operations/2011-final-value-of-variable-after-performing-operations.kt
  2011-final-value-of-variable-after-performing-operations/NOTES.md
  2011-final-value-of-variable-after-performing-operations/README.md
Labels: 🎉 All pass

#61 Day 6 & 7 & 8
  1108-defanging-an-ip-address/NOTES.md
  1108-defanging-an-ip-address/README.md
  1587-bank-account-summary-ii/1587-bank-account-summary-ii.sql
  1587-bank-account-summary-ii/NOTES.md
  1587-bank-account-summary-ii/README.md
  1741-find-total-time-spent-by-each-employee/NOTES.md
  1741-find-total-time-spent-by-each-employee/README.md
  1768-merge-strings-alternately/NOTES.md
  1768-merge-strings-alternately/README.md
  1859-sorting-the-sentence/1859-sorting-the-sentence.java
  1859-sorting-the-sentence/NOTES.md
  1859-sorting-the-sentence/README.md
  1876-substrings-of-size-three-with-distinct-characters/NOTES.md
  1876-substrings-of-size-three-with-distinct-characters/README.md
  1920-build-array-from-permutation/README.md
  2011-final-value-of-variable-after-performing-operations/NOTES.md
  2011-final-value-of-variable-after-performing-operations/README.md
  2255-count-prefixes-of-a-given-string/NOTES.md
  2255-count-prefixes-of-a-given-string/README.md
Labels: 😥 hitted

#65 Day 9
  0485-max-consecutive-ones/NOTES.md
  0485-max-consecutive-ones/README.md
  0495-teemo-attacking/0495-teemo-attacking.py
  0495-teemo-attacking/NOTES.md
  0495-teemo-attacking/README.md
  1407-top-travellers/1407-top-travellers.sql
  1407-top-travellers/NOTES.md
  1407-top-travellers/README.md
  1470-shuffle-the-array/1470-shuffle-the-array.py
  1470-shuffle-the-array/NOTES.md
  1470-shuffle-the-array/README.md
Labels: 🎉 All pass

#63 day 9
  0485-max-consecutive-ones/0485-max-consecutive-ones.kt
  0485-max-consecutive-ones/NOTES.md
  0485-max-consecutive-ones/README.md
  0495-teemo-attacking/0495-teemo-attacking.kt
  0495-teemo-attacking/NOTES.md
  0495-teemo-attacking/README.md
  1407-top-travellers/1407-top-travellers.sql
  1407-top-travellers/NOTES.md
  1407-top-travellers/README.md
  1470-shuffle-the-array/1470-shuffle-the-array.kt
  1470-shuffle-the-array/NOTES.md
  1470-shuffle-the-array/README.md
Labels: 🎉 All pass

#64 Day 9 & 10
  .github/ISSUE_TEMPLATE/custom.yaml
  0178-rank-scores/0178-rank-scores.sql
  0178-rank-scores/NOTES.md
  0178-rank-scores/README.md
  0328-odd-even-linked-list/0328-odd-even-linked-list.java
  0328-odd-even-linked-list/NOTES.md
  0328-odd-even-linked-list/README.md
  0485-max-consecutive-ones/0485-max-consecutive-ones.java
  0485-max-consecutive-ones/NOTES.md
  0485-max-consecutive-ones/README.md
  0495-teemo-attacking/0495-teemo-attacking.java
  0495-teemo-attacking/NOTES.md
  0495-teemo-attacking/README.md
  0682-baseball-game/0682-baseball-game.java
  0682-baseball-game/NOTES.md
  0682-baseball-game/README.md
  0938-range-sum-of-bst/0938-range-sum-of-bst.java
  0938-range-sum-of-bst/README.md
  1407-top-travellers/1407-top-travellers.sql
  1407-top-travellers/NOTES.md
  1407-top-travellers/README.md
  1470-shuffle-the-array/1470-shuffle-the-array.java
  1470-shuffle-the-array/NOTES.md
  1470-shuffle-the-array/README.md
  1512-number-of-good-pairs/1512-number-of-good-pairs.java
  1512-number-of-good-pairs/NOTES.md
  1512-number-of-good-pairs/README.md
  2206-divide-array-into-equal-pairs/2206-divide-array-into-equal-pairs.java
  2206-divide-array-into-equal-pairs/NOTES.md
  2206-divide-array-into-equal-pairs/README.md
  README.md
Labels: 🎉 All pass

#68 day 10
  0178-rank-scores/0178-rank-scores.sql
  0178-rank-scores/NOTES.md
  0178-rank-scores/README.md
  0682-baseball-game/0682-baseball-game.kt
  0682-baseball-game/NOTES.md
  0682-baseball-game/README.md
  1512-number-of-good-pairs/1512-number-of-good-pairs.kt
  1512-number-of-good-pairs/NOTES.md
  1512-number-of-good-pairs/README.md
  2206-divide-array-into-equal-pairs/2206-divide-array-into-equal-pairs.kt
  2206-divide-array-into-equal-pairs/NOTES.md
  2206-divide-array-into-equal-pairs/README.md
Labels: 🎉 All pass

#67 Day 9 & 10
  0178-rank-scores/README.md
  0485-max-consecutive-ones/NOTES.md
  0485-max-consecutive-ones/README.md
  0495-teemo-attacking/0495-teemo-attacking.java
  0495-teemo-attacking/NOTES.md
  0495-teemo-attacking/README.md
  0682-baseball-game/0682-baseball-game.java
  0682-baseball-game/NOTES.md
  0682-baseball-game/README.md
  1407-top-travellers/NOTES.md
  1407-top-travellers/README.md
  1470-shuffle-the-array/NOTES.md
  1470-shuffle-the-array/README.md
  1512-number-of-good-pairs/NOTES.md
  1512-number-of-good-pairs/README.md
  2206-divide-array-into-equal-pairs/NOTES.md
  2206-divide-array-into-equal-pairs/README.md
Labels: 🎉 All pass

#70 day 9 & 10
  0178-rank-scores/NOTES.md
  0178-rank-scores/README.md
  0485-max-consecutive-ones/0485-max-consecutive-ones.java
  0485-max-consecutive-ones/NOTES.md
  0485-max-consecutive-ones/README.md
  0495-teemo-attacking/0495-teemo-attacking.java
  0495-teemo-attacking/NOTES.md
  0495-teemo-attacking/README.md
  0682-baseball-game/0682-baseball-game.java
  0682-baseball-game/NOTES.md
  0682-baseball-game/README.md
  1407-top-travellers/1407-top-travellers.sql
  1407-top-travellers/NOTES.md
  1407-top-travellers/README.md
  1470-shuffle-the-array/1470-shuffle-the-array.java
  1470-shuffle-the-array/NOTES.md
  1470-shuffle-the-array/README.md
  1512-number-of-good-pairs/1512-number-of-good-pairs.java
  1512-number-of-good-pairs/NOTES.md
  1512-number-of-good-pairs/README.md
  2206-divide-array-into-equal-pairs/2206-divide-array-into-equal-pairs.java
  2206-divide-array-into-equal-pairs/NOTES.md
  2206-divide-array-into-equal-pairs/README.md
Labels: 🎉 All pass

#72 Day 10 & 11
  0178-rank-scores/0178-rank-scores.sql
  0178-rank-scores/NOTES.md
  0178-rank-scores/README.md
  0268-missing-number/0268-missing-number.py
  0268-missing-number/NOTES.md
  0268-missing-number/README.md
  0682-baseball-game/0682-baseball-game.py
  0682-baseball-game/NOTES.md
  0682-baseball-game/README.md
  1512-number-of-good-pairs/1512-number-of-good-pairs.py
  1512-number-of-good-pairs/NOTES.md
  1512-number-of-good-pairs/README.md
  1672-richest-customer-wealth/1672-richest-customer-wealth.py
  1672-richest-customer-wealth/NOTES.md
  1672-richest-customer-wealth/README.md
  1816-truncate-sentence/NOTES.md
  1816-truncate-sentence/README.md
  1890-the-latest-login-in-2020/1890-the-latest-login-in-2020.sql
  1890-the-latest-login-in-2020/NOTES.md
  1890-the-latest-login-in-2020/README.md
  2206-divide-array-into-equal-pairs/2206-divide-array-into-equal-pairs.py
  2206-divide-array-into-equal-pairs/NOTES.md
  2206-divide-array-into-equal-pairs/README.md
Labels: 🎉 All pass

#73 Day 11
  0268-missing-number/0268-missing-number.java
  0268-missing-number/NOTES.md
  0268-missing-number/README.md
  1672-richest-customer-wealth/NOTES.md
  1672-richest-customer-wealth/README.md
  1816-truncate-sentence/README.md
  1890-the-latest-login-in-2020/1890-the-latest-login-in-2020.sql
  1890-the-latest-login-in-2020/NOTES.md
  1890-the-latest-login-in-2020/README.md
Labels: 🎉 All pass

#74 day 11
  0268-missing-number/0268-missing-number.kt
  0268-missing-number/NOTES.md
  0268-missing-number/README.md
  1672-richest-customer-wealth/1672-richest-customer-wealth.kt
  1672-richest-customer-wealth/NOTES.md
  1672-richest-customer-wealth/README.md
  1816-truncate-sentence/1816-truncate-sentence.kt
  1816-truncate-sentence/NOTES.md
  1816-truncate-sentence/README.md
  1890-the-latest-login-in-2020/1890-the-latest-login-in-2020.sql
  1890-the-latest-login-in-2020/NOTES.md
  1890-the-latest-login-in-2020/README.md
Labels: 🎉 All pass

#78 Day 12
  1572-matrix-diagonal-sum/1572-matrix-diagonal-sum.java
  1572-matrix-diagonal-sum/NOTES.md
  1572-matrix-diagonal-sum/README.md
  1684-count-the-number-of-consistent-strings/NOTES.md
  1684-count-the-number-of-consistent-strings/README.md
  1877-minimize-maximum-pair-sum-in-array/1877-minimize-maximum-pair-sum-in-array.java
  1877-minimize-maximum-pair-sum-in-array/NOTES.md
  1877-minimize-maximum-pair-sum-in-array/README.md
Labels: 🎉 All pass, 😥 hitted

#77 Day 12
  0626-exchange-seats/0626-exchange-seats.sql
  0626-exchange-seats/NOTES.md
  0626-exchange-seats/README.md
  1572-matrix-diagonal-sum/1572-matrix-diagonal-sum.py
  1572-matrix-diagonal-sum/NOTES.md
  1572-matrix-diagonal-sum/README.md
  1684-count-the-number-of-consistent-strings/1684-count-the-number-of-consistent-strings.py
  1684-count-the-number-of-consistent-strings/NOTES.md
  1684-count-the-number-of-consistent-strings/README.md
  1877-minimize-maximum-pair-sum-in-array/1877-minimize-maximum-pair-sum-in-array.py
  1877-minimize-maximum-pair-sum-in-array/NOTES.md
  1877-minimize-maximum-pair-sum-in-array/README.md
Labels: 🎉 All pass

#79 Day 12
  .github/ISSUE_TEMPLATE/custom.yaml
  0617-merge-two-binary-trees/0617-merge-two-binary-trees.java
  0617-merge-two-binary-trees/NOTES.md
  0617-merge-two-binary-trees/README.md
  0872-leaf-similar-trees/0872-leaf-similar-trees.java
  0872-leaf-similar-trees/NOTES.md
  0872-leaf-similar-trees/README.md
  1026-maximum-difference-between-node-and-ancestor/1026-maximum-difference-between-node-and-ancestor.java
  1026-maximum-difference-between-node-and-ancestor/NOTES.md
  1026-maximum-difference-between-node-and-ancestor/README.md
  1339-maximum-product-of-splitted-binary-tree/1339-maximum-product-of-splitted-binary-tree.java
  1339-maximum-product-of-splitted-binary-tree/NOTES.md
  1339-maximum-product-of-splitted-binary-tree/README.md
  1572-matrix-diagonal-sum/1572-matrix-diagonal-sum.java
  1572-matrix-diagonal-sum/NOTES.md
  1572-matrix-diagonal-sum/README.md
  1684-count-the-number-of-consistent-strings/1684-count-the-number-of-consistent-strings.java
  1684-count-the-number-of-consistent-strings/NOTES.md
  1684-count-the-number-of-consistent-strings/README.md
  1877-minimize-maximum-pair-sum-in-array/1877-minimize-maximum-pair-sum-in-array.java
  1877-minimize-maximum-pair-sum-in-array/NOTES.md
  1877-minimize-maximum-pair-sum-in-array/README.md
Labels: 🎉 All pass, 😥 hitted

#88 Day 6 & 7
  0890-find-and-replace-pattern/0890-find-and-replace-pattern.java
  0890-find-and-replace-pattern/NOTES.md
  0890-find-and-replace-pattern/README.md
  1108-defanging-an-ip-address/1108-defanging-an-ip-address.java
  1108-defanging-an-ip-address/NOTES.md
  1108-defanging-an-ip-address/README.md
  1179-reformat-department-table/1179-reformat-department-table.sql
  1179-reformat-department-table/NOTES.md
  1179-reformat-department-table/README.md
  1741-find-total-time-spent-by-each-employee/1741-find-total-time-spent-by-each-employee.sql
  1741-find-total-time-spent-by-each-employee/NOTES.md
  1741-find-total-time-spent-by-each-employee/README.md
  1768-merge-strings-alternately/1768-merge-strings-alternately.java
  1768-merge-strings-alternately/NOTES.md
  1768-merge-strings-alternately/README.md
  1859-sorting-the-sentence/1859-sorting-the-sentence.java
  1859-sorting-the-sentence/NOTES.md
  1859-sorting-the-sentence/README.md
  1876-substrings-of-size-three-with-distinct-characters/1876-substrings-of-size-three-with-distinct-characters.java
  1876-substrings-of-size-three-with-distinct-characters/NOTES.md
  1876-substrings-of-size-three-with-distinct-characters/README.md
  2255-count-prefixes-of-a-given-string/2255-count-prefixes-of-a-given-string.java
  2255-count-prefixes-of-a-given-string/NOTES.md
  2255-count-prefixes-of-a-given-string/README.md
Labels: 🎉 All pass

#87 Day16
  0349-intersection-of-two-arrays/0349-intersection-of-two-arrays.java
  0349-intersection-of-two-arrays/NOTES.md
  0349-intersection-of-two-arrays/README.md
  2032-two-out-of-three/2032-two-out-of-three.java
  2032-two-out-of-three/NOTES.md
  2032-two-out-of-three/README.md
  2351-first-letter-to-appear-twice/NOTES.md
  2351-first-letter-to-appear-twice/README.md
Labels: 🎉 All pass

#89 Day 8
  1587-bank-account-summary-ii/1587-bank-account-summary-ii.sql
  1587-bank-account-summary-ii/NOTES.md
  1587-bank-account-summary-ii/README.md
  1920-build-array-from-permutation/1920-build-array-from-permutation.java
  1920-build-array-from-permutation/NOTES.md
  1920-build-array-from-permutation/README.md
  1929-concatenation-of-array/1929-concatenation-of-array.java
  1929-concatenation-of-array/NOTES.md
  1929-concatenation-of-array/README.md
  2011-final-value-of-variable-after-performing-operations/2011-final-value-of-variable-after-performing-operations.java
  2011-final-value-of-variable-after-performing-operations/NOTES.md
  2011-final-value-of-variable-after-performing-operations/README.md
Labels: 🎉 All pass

#90 day 13
  0860-lemonade-change/0860-lemonade-change.kt
  0860-lemonade-change/NOTES.md
  0860-lemonade-change/README.md
  1393-capital-gain-loss/1393-capital-gain-loss.sql
  1393-capital-gain-loss/NOTES.md
  1393-capital-gain-loss/README.md
  1763-longest-nice-substring/1763-longest-nice-substring.kt
  1763-longest-nice-substring/NOTES.md
  1763-longest-nice-substring/README.md
  2347-best-poker-hand/2347-best-poker-hand.kt
  2347-best-poker-hand/NOTES.md
  2347-best-poker-hand/README.md
Labels: 🎉 All pass

#91 day 14
  0303-range-sum-query-immutable/0303-range-sum-query-immutable.kt
  0303-range-sum-query-immutable/NOTES.md
  0303-range-sum-query-immutable/README.md
  1122-relative-sort-array/1122-relative-sort-array.kt
  1122-relative-sort-array/NOTES.md
  1122-relative-sort-array/README.md
  1158-market-analysis-i/1158-market-analysis-i.sql
  1158-market-analysis-i/NOTES.md
  1158-market-analysis-i/README.md
  1979-find-greatest-common-divisor-of-array/1979-find-greatest-common-divisor-of-array.kt
  1979-find-greatest-common-divisor-of-array/NOTES.md
  1979-find-greatest-common-divisor-of-array/README.md
Labels: 🎉 All pass

#93 day 15
  0070-climbing-stairs/0070-climbing-stairs.kt
  0070-climbing-stairs/NOTES.md
  0070-climbing-stairs/README.md
  0184-department-highest-salary/0184-department-highest-salary.sql
  0184-department-highest-salary/NOTES.md
  0184-department-highest-salary/README.md
  1207-unique-number-of-occurrences/1207-unique-number-of-occurrences.kt
  1207-unique-number-of-occurrences/NOTES.md
  1207-unique-number-of-occurrences/README.md
  1742-maximum-number-of-balls-in-a-box/1742-maximum-number-of-balls-in-a-box.kt
  1742-maximum-number-of-balls-in-a-box/NOTES.md
  1742-maximum-number-of-balls-in-a-box/README.md
Labels: 🎉 All pass

#85 Day 13 & 14 & 15 & 16
  0070-climbing-stairs/NOTES.md
  0070-climbing-stairs/README.md
  0184-department-highest-salary/NOTES.md
  0184-department-highest-salary/README.md
  0303-range-sum-query-immutable/NOTES.md
  0303-range-sum-query-immutable/README.md
  0349-intersection-of-two-arrays/NOTES.md
  0349-intersection-of-two-arrays/README.md
  0860-lemonade-change/NOTES.md
  0860-lemonade-change/README.md
  1122-relative-sort-array/NOTES.md
  1122-relative-sort-array/README.md
  1158-market-analysis-i/1158-market-analysis-i.sql
  1158-market-analysis-i/NOTES.md
  1158-market-analysis-i/README.md
  1207-unique-number-of-occurrences/NOTES.md
  1207-unique-number-of-occurrences/README.md
  1393-capital-gain-loss/1393-capital-gain-loss.sql
  1393-capital-gain-loss/NOTES.md
  1393-capital-gain-loss/README.md
  1742-maximum-number-of-balls-in-a-box/NOTES.md
  1742-maximum-number-of-balls-in-a-box/README.md
  1763-longest-nice-substring/README.md
  1979-find-greatest-common-divisor-of-array/NOTES.md
  1979-find-greatest-common-divisor-of-array/README.md
  2032-two-out-of-three/NOTES.md
  2032-two-out-of-three/README.md
  2347-best-poker-hand/NOTES.md
  2347-best-poker-hand/README.md
  2351-first-letter-to-appear-twice/NOTES.md
  2351-first-letter-to-appear-twice/README.md
Labels: 👻 miss algorithm, 🎉 All pass

#100 day 17
  0012-integer-to-roman/NOTES.md
  0012-integer-to-roman/README.md
  0180-consecutive-numbers/0180-consecutive-numbers.sql
  0180-consecutive-numbers/NOTES.md
  0180-consecutive-numbers/README.md
  0496-next-greater-element-i/0496-next-greater-element-i.kt
  0496-next-greater-element-i/NOTES.md
  0496-next-greater-element-i/README.md
  1002-find-common-characters/1002-find-common-characters.kt
  1002-find-common-characters/NOTES.md
  1002-find-common-characters/README.md
Labels: 🎉 All pass

#103 Day17 & 18
  0012-integer-to-roman/0012-integer-to-roman.java
  0012-integer-to-roman/NOTES.md
  0012-integer-to-roman/README.md
  0177-nth-highest-salary/0177-nth-highest-salary.sql
  0177-nth-highest-salary/NOTES.md
  0177-nth-highest-salary/README.md
  0496-next-greater-element-i/0496-next-greater-element-i.java
  0496-next-greater-element-i/NOTES.md
  0496-next-greater-element-i/README.md
  0506-relative-ranks/0506-relative-ranks.js
  0506-relative-ranks/NOTES.md
  0506-relative-ranks/README.md
  0541-reverse-string-ii/0541-reverse-string-ii.java
  0541-reverse-string-ii/NOTES.md
  0541-reverse-string-ii/README.md
  0561-array-partition/0561-array-partition.java
  0561-array-partition/NOTES.md
  0561-array-partition/README.md
  0931-minimum-falling-path-sum/0931-minimum-falling-path-sum.java
  0931-minimum-falling-path-sum/NOTES.md
  0931-minimum-falling-path-sum/README.md
Labels: 🎉 All pass

#97 Day 17
  0012-integer-to-roman/0012-integer-to-roman.java
  0012-integer-to-roman/NOTES.md
  0012-integer-to-roman/README.md
  0496-next-greater-element-i/NOTES.md
  0496-next-greater-element-i/README.md
  0506-relative-ranks/0506-relative-ranks.java
  0506-relative-ranks/NOTES.md
  0506-relative-ranks/README.md
  0541-reverse-string-ii/0541-reverse-string-ii.java
  0541-reverse-string-ii/NOTES.md
  0541-reverse-string-ii/README.md
  README.md
Labels: 🎉 All pass

#102 Day 9
  0485-max-consecutive-ones/0485-max-consecutive-ones.java
  0485-max-consecutive-ones/NOTES.md
  0485-max-consecutive-ones/README.md
  0495-teemo-attacking/0495-teemo-attacking.java
  0495-teemo-attacking/NOTES.md
  0495-teemo-attacking/README.md
  1407-top-travellers/NOTES.md
  1407-top-travellers/README.md
  1470-shuffle-the-array/1470-shuffle-the-array.java
  1470-shuffle-the-array/NOTES.md
  1470-shuffle-the-array/README.md
Labels: 🎉 All pass

#106 day 10
  0178-rank-scores/0178-rank-scores.sql
  0178-rank-scores/NOTES.md
  0178-rank-scores/README.md
  0682-baseball-game/0682-baseball-game.java
  0682-baseball-game/NOTES.md
  0682-baseball-game/README.md
  1512-number-of-good-pairs/NOTES.md
  1512-number-of-good-pairs/README.md
  1672-richest-customer-wealth/1672-richest-customer-wealth.java
  1672-richest-customer-wealth/NOTES.md
  1672-richest-customer-wealth/README.md
  2206-divide-array-into-equal-pairs/2206-divide-array-into-equal-pairs.java
  2206-divide-array-into-equal-pairs/NOTES.md
  2206-divide-array-into-equal-pairs/README.md
Labels: 🎉 All pass

#107 Day 19 & 20
  0049-group-anagrams/0049-group-anagrams.java
  0049-group-anagrams/NOTES.md
  0049-group-anagrams/README.md
  0150-evaluate-reverse-polish-notation/0150-evaluate-reverse-polish-notation.js
  0150-evaluate-reverse-polish-notation/NOTES.md
  0150-evaluate-reverse-polish-notation/README.md
  0232-implement-queue-using-stacks/0232-implement-queue-using-stacks.java
  0232-implement-queue-using-stacks/NOTES.md
  0232-implement-queue-using-stacks/README.md
  0290-word-pattern/0290-word-pattern.java
  0290-word-pattern/NOTES.md
  0290-word-pattern/README.md
  0739-daily-temperatures/0739-daily-temperatures.java
  0739-daily-temperatures/NOTES.md
  0739-daily-temperatures/README.md
  1275-find-winner-on-a-tic-tac-toe-game/1275-find-winner-on-a-tic-tac-toe-game.java
  1275-find-winner-on-a-tic-tac-toe-game/NOTES.md
  1275-find-winner-on-a-tic-tac-toe-game/README.md
  1436-destination-city/1436-destination-city.js
  1436-destination-city/NOTES.md
  1436-destination-city/README.md
  1656-design-an-ordered-stream/1656-design-an-ordered-stream.java
  1656-design-an-ordered-stream/NOTES.md
  1656-design-an-ordered-stream/README.md
  2022-convert-1d-array-into-2d-array/2022-convert-1d-array-into-2d-array.java
  2022-convert-1d-array-into-2d-array/NOTES.md
  2022-convert-1d-array-into-2d-array/README.md
  2023-number-of-pairs-of-strings-with-concatenation-equal-to-target/2023-number-of-pairs-of-strings-with-concatenation-equal-to-target.java
  2023-number-of-pairs-of-strings-with-concatenation-equal-to-target/NOTES.md
  2023-number-of-pairs-of-strings-with-concatenation-equal-to-target/README.md
  2341-maximum-number-of-pairs-in-array/NOTES.md
  2341-maximum-number-of-pairs-in-array/README.md
  2442-count-number-of-distinct-integers-after-reverse-operations/2442-count-number-of-distinct-integers-after-reverse-operations.js
  2442-count-number-of-distinct-integers-after-reverse-operations/NOTES.md
  2442-count-number-of-distinct-integers-after-reverse-operations/README.md
Labels: 🎉 All pass

#110 day 18
  0177-nth-highest-salary/0177-nth-highest-salary.sql
  0177-nth-highest-salary/NOTES.md
  0177-nth-highest-salary/README.md
  0506-relative-ranks/0506-relative-ranks.kt
  0506-relative-ranks/NOTES.md
  0506-relative-ranks/README.md
  0541-reverse-string-ii/0541-reverse-string-ii.kt
  0541-reverse-string-ii/NOTES.md
  0541-reverse-string-ii/README.md
  0561-array-partition/0561-array-partition.kt
  0561-array-partition/NOTES.md
  0561-array-partition/README.md
Labels: 🎉 All pass

#111 day 19
  0262-trips-and-users/0262-trips-and-users.sql
  0262-trips-and-users/NOTES.md
  0262-trips-and-users/README.md
  1436-destination-city/1436-destination-city.kt
  1436-destination-city/NOTES.md
  1436-destination-city/README.md
  1656-design-an-ordered-stream/1656-design-an-ordered-stream.kt
  1656-design-an-ordered-stream/NOTES.md
  1656-design-an-ordered-stream/README.md
  2442-count-number-of-distinct-integers-after-reverse-operations/2442-count-number-of-distinct-integers-after-reverse-operations.kt
  2442-count-number-of-distinct-integers-after-reverse-operations/README.md
Labels: 🎉 All pass

#112 day 11
  0268-missing-number/0268-missing-number.java
  0268-missing-number/NOTES.md
  0268-missing-number/README.md
  1816-truncate-sentence/1816-truncate-sentence.java
  1816-truncate-sentence/NOTES.md
  1816-truncate-sentence/README.md
  1890-the-latest-login-in-2020/1890-the-latest-login-in-2020.sql
  1890-the-latest-login-in-2020/NOTES.md
  1890-the-latest-login-in-2020/README.md
Labels: 🎉 All pass

#115 Day 13 & Day 14 & Day 15
  0070-climbing-stairs/0070-climbing-stairs.py
  0070-climbing-stairs/NOTES.md
  0070-climbing-stairs/README.md
  0184-department-highest-salary/0184-department-highest-salary.sql
  0184-department-highest-salary/NOTES.md
  0184-department-highest-salary/README.md
  0303-range-sum-query-immutable/0303-range-sum-query-immutable.py
  0303-range-sum-query-immutable/NOTES.md
  0303-range-sum-query-immutable/README.md
  0860-lemonade-change/0860-lemonade-change.py
  0860-lemonade-change/NOTES.md
  0860-lemonade-change/README.md
  1122-relative-sort-array/1122-relative-sort-array.py
  1122-relative-sort-array/NOTES.md
  1122-relative-sort-array/README.md
  1158-market-analysis-i/NOTES.md
  1158-market-analysis-i/README.md
  1207-unique-number-of-occurrences/1207-unique-number-of-occurrences.py
  1207-unique-number-of-occurrences/NOTES.md
  1207-unique-number-of-occurrences/README.md
  1393-capital-gain-loss/1393-capital-gain-loss.sql
  1393-capital-gain-loss/NOTES.md
  1393-capital-gain-loss/README.md
  1742-maximum-number-of-balls-in-a-box/1742-maximum-number-of-balls-in-a-box.py
  1742-maximum-number-of-balls-in-a-box/NOTES.md
  1742-maximum-number-of-balls-in-a-box/README.md
  1763-longest-nice-substring/1763-longest-nice-substring.py
  1763-longest-nice-substring/NOTES.md
  1763-longest-nice-substring/README.md
  1979-find-greatest-common-divisor-of-array/1979-find-greatest-common-divisor-of-array.py
  1979-find-greatest-common-divisor-of-array/NOTES.md
  1979-find-greatest-common-divisor-of-array/README.md
  2347-best-poker-hand/2347-best-poker-hand.py
  2347-best-poker-hand/NOTES.md
  2347-best-poker-hand/README.md
Labels: 🎉 All pass

#116 day 20
  0049-group-anagrams/0049-group-anagrams.kt
  0049-group-anagrams/NOTES.md
  0049-group-anagrams/README.md
  0290-word-pattern/0290-word-pattern.kt
  0290-word-pattern/NOTES.md
  0290-word-pattern/README.md
  2341-maximum-number-of-pairs-in-array/2341-maximum-number-of-pairs-in-array.kt
  2341-maximum-number-of-pairs-in-array/NOTES.md
  2341-maximum-number-of-pairs-in-array/README.md
Labels: 🎉 All pass

#119 day 21
  1346-check-if-n-and-its-double-exist/1346-check-if-n-and-its-double-exist.kt
  1346-check-if-n-and-its-double-exist/NOTES.md
  1346-check-if-n-and-its-double-exist/README.md
  1814-count-nice-pairs-in-an-array/1814-count-nice-pairs-in-an-array.java
  1814-count-nice-pairs-in-an-array/1814-count-nice-pairs-in-an-array.kt
  1814-count-nice-pairs-in-an-array/NOTES.md
  1814-count-nice-pairs-in-an-array/README.md
  2099-find-subsequence-of-length-k-with-the-largest-sum/2099-find-subsequence-of-length-k-with-the-largest-sum.kt
  2099-find-subsequence-of-length-k-with-the-largest-sum/NOTES.md
  2099-find-subsequence-of-length-k-with-the-largest-sum/README.md
Labels: 🎉 All pass

#120 week 3
  0012-integer-to-roman/NOTES.md
  0012-integer-to-roman/README.md
  0049-group-anagrams/0049-group-anagrams.kt
  0049-group-anagrams/NOTES.md
  0049-group-anagrams/README.md
  0177-nth-highest-salary/0177-nth-highest-salary.sql
  0177-nth-highest-salary/NOTES.md
  0177-nth-highest-salary/README.md
  0180-consecutive-numbers/0180-consecutive-numbers.sql
  0180-consecutive-numbers/NOTES.md
  0180-consecutive-numbers/README.md
  0262-trips-and-users/0262-trips-and-users.sql
  0262-trips-and-users/NOTES.md
  0262-trips-and-users/README.md
  0290-word-pattern/0290-word-pattern.kt
  0290-word-pattern/NOTES.md
  0290-word-pattern/README.md
  0496-next-greater-element-i/0496-next-greater-element-i.kt
  0496-next-greater-element-i/NOTES.md
  0496-next-greater-element-i/README.md
  0506-relative-ranks/0506-relative-ranks.kt
  0506-relative-ranks/NOTES.md
  0506-relative-ranks/README.md
  0541-reverse-string-ii/0541-reverse-string-ii.kt
  0541-reverse-string-ii/NOTES.md
  0541-reverse-string-ii/README.md
  0561-array-partition/0561-array-partition.kt
  0561-array-partition/NOTES.md
  0561-array-partition/README.md
  1002-find-common-characters/1002-find-common-characters.kt
  1002-find-common-characters/NOTES.md
  1002-find-common-characters/README.md
  1346-check-if-n-and-its-double-exist/1346-check-if-n-and-its-double-exist.kt
  1346-check-if-n-and-its-double-exist/NOTES.md
  1346-check-if-n-and-its-double-exist/README.md
  1436-destination-city/1436-destination-city.kt
  1436-destination-city/NOTES.md
  1436-destination-city/README.md
  1656-design-an-ordered-stream/1656-design-an-ordered-stream.kt
  1656-design-an-ordered-stream/NOTES.md
  1656-design-an-ordered-stream/README.md
  1814-count-nice-pairs-in-an-array/1814-count-nice-pairs-in-an-array.java
  1814-count-nice-pairs-in-an-array/1814-count-nice-pairs-in-an-array.kt
  1814-count-nice-pairs-in-an-array/NOTES.md
  1814-count-nice-pairs-in-an-array/README.md
  2099-find-subsequence-of-length-k-with-the-largest-sum/2099-find-subsequence-of-length-k-with-the-largest-sum.kt
  2099-find-subsequence-of-length-k-with-the-largest-sum/NOTES.md
  2099-find-subsequence-of-length-k-with-the-largest-sum/README.md
  2341-maximum-number-of-pairs-in-array/2341-maximum-number-of-pairs-in-array.kt
  2341-maximum-number-of-pairs-in-array/NOTES.md
  2341-maximum-number-of-pairs-in-array/README.md
  2442-count-number-of-distinct-integers-after-reverse-operations/2442-count-number-of-distinct-integers-after-reverse-operations.kt
  2442-count-number-of-distinct-integers-after-reverse-operations/README.md
Labels: ❔ Question

#122 Day 12
  0626-exchange-seats/0626-exchange-seats.sql
  0626-exchange-seats/NOTES.md
  0626-exchange-seats/README.md
  1572-matrix-diagonal-sum/1572-matrix-diagonal-sum.java
  1572-matrix-diagonal-sum/NOTES.md
  1572-matrix-diagonal-sum/README.md
  1684-count-the-number-of-consistent-strings/1684-count-the-number-of-consistent-strings.java
  1684-count-the-number-of-consistent-strings/NOTES.md
  1684-count-the-number-of-consistent-strings/README.md
  1877-minimize-maximum-pair-sum-in-array/1877-minimize-maximum-pair-sum-in-array.java
  1877-minimize-maximum-pair-sum-in-array/NOTES.md
  1877-minimize-maximum-pair-sum-in-array/README.md
Labels: 🎉 All pass

#108 Day 18 & Day 19 & Day 20 & Day 21
  0049-group-anagrams/0049-group-anagrams.java
  0049-group-anagrams/NOTES.md
  0049-group-anagrams/README.md
  0290-word-pattern/NOTES.md
  0290-word-pattern/README.md
  0561-array-partition/NOTES.md
  0561-array-partition/README.md
  1346-check-if-n-and-its-double-exist/NOTES.md
  1346-check-if-n-and-its-double-exist/README.md
  1436-destination-city/NOTES.md
  1436-destination-city/README.md
  1656-design-an-ordered-stream/README.md
  1814-count-nice-pairs-in-an-array/NOTES.md
  1814-count-nice-pairs-in-an-array/README.md
  2099-find-subsequence-of-length-k-with-the-largest-sum/NOTES.md
  2099-find-subsequence-of-length-k-with-the-largest-sum/README.md
  2236-root-equals-sum-of-children/NOTES.md
  2236-root-equals-sum-of-children/README.md
  2341-maximum-number-of-pairs-in-array/NOTES.md
  2341-maximum-number-of-pairs-in-array/README.md
  2442-count-number-of-distinct-integers-after-reverse-operations/NOTES.md
  2442-count-number-of-distinct-integers-after-reverse-operations/README.md
Labels: 🎉 All pass

#123 day 22
  0185-department-top-three-salaries/0185-department-top-three-salaries.sql
  0185-department-top-three-salaries/NOTES.md
  0559-maximum-depth-of-n-ary-tree/0559-maximum-depth-of-n-ary-tree.kt
  0559-maximum-depth-of-n-ary-tree/NOTES.md
  0559-maximum-depth-of-n-ary-tree/README.md
  0617-merge-two-binary-trees/0617-merge-two-binary-trees.kt
  0617-merge-two-binary-trees/NOTES.md
  0617-merge-two-binary-trees/README.md
  2236-root-equals-sum-of-children/2236-root-equals-sum-of-children.kt
  2236-root-equals-sum-of-children/NOTES.md
  2236-root-equals-sum-of-children/README.md
Labels: 🎉 All pass

#127 day 13
  0860-lemonade-change/0860-lemonade-change.java
  0860-lemonade-change/NOTES.md
  0860-lemonade-change/README.md
  1393-capital-gain-loss/NOTES.md
  1393-capital-gain-loss/README.md
  1763-longest-nice-substring/1763-longest-nice-substring.java
  1763-longest-nice-substring/NOTES.md
  1763-longest-nice-substring/README.md
  2347-best-poker-hand/2347-best-poker-hand.java
  2347-best-poker-hand/NOTES.md
  2347-best-poker-hand/README.md
Labels: 🎉 All pass

#128 day 23
  0700-search-in-a-binary-search-tree/NOTES.md
  0700-search-in-a-binary-search-tree/README.md
  0897-increasing-order-search-tree/0897-increasing-order-search-tree.kt
  0897-increasing-order-search-tree/NOTES.md
  0897-increasing-order-search-tree/README.md
  0938-range-sum-of-bst/0938-range-sum-of-bst.kt
  0938-range-sum-of-bst/NOTES.md
  0938-range-sum-of-bst/README.md
  0979-distribute-coins-in-binary-tree/0979-distribute-coins-in-binary-tree.kt
  0979-distribute-coins-in-binary-tree/NOTES.md
  0979-distribute-coins-in-binary-tree/README.md
Labels: 🎉 All pass

#130 day 23 & day 24
  0257-binary-tree-paths/0257-binary-tree-paths.kt
  0257-binary-tree-paths/NOTES.md
  0257-binary-tree-paths/README.md
  0637-average-of-levels-in-binary-tree/NOTES.md
  0637-average-of-levels-in-binary-tree/README.md
  0700-search-in-a-binary-search-tree/NOTES.md
  0700-search-in-a-binary-search-tree/README.md
  0897-increasing-order-search-tree/0897-increasing-order-search-tree.java
  0897-increasing-order-search-tree/NOTES.md
  0897-increasing-order-search-tree/README.md
  0938-range-sum-of-bst/NOTES.md
  0938-range-sum-of-bst/README.md
  0965-univalued-binary-tree/NOTES.md
  0965-univalued-binary-tree/README.md
Labels: 🎉 All pass

#132 Day 23 & 24
  0257-binary-tree-paths/0257-binary-tree-paths.java
  0257-binary-tree-paths/NOTES.md
  0257-binary-tree-paths/README.md
  0637-average-of-levels-in-binary-tree/0637-average-of-levels-in-binary-tree.java
  0637-average-of-levels-in-binary-tree/NOTES.md
  0637-average-of-levels-in-binary-tree/README.md
  0700-search-in-a-binary-search-tree/0700-search-in-a-binary-search-tree.java
  0700-search-in-a-binary-search-tree/NOTES.md
  0700-search-in-a-binary-search-tree/README.md
  0897-increasing-order-search-tree/0897-increasing-order-search-tree.java
  0897-increasing-order-search-tree/NOTES.md
  0897-increasing-order-search-tree/README.md
  0938-range-sum-of-bst/NOTES.md
  0965-univalued-binary-tree/0965-univalued-binary-tree.java
  0965-univalued-binary-tree/NOTES.md
  0965-univalued-binary-tree/README.md
Labels: 🎉 All pass

#135 Day 19 & Day 20 & Day 21
  0049-group-anagrams/NOTES.md
  0049-group-anagrams/README.md
  0290-word-pattern/0290-word-pattern.py
  0290-word-pattern/NOTES.md
  0290-word-pattern/README.md
  1346-check-if-n-and-its-double-exist/1346-check-if-n-and-its-double-exist.py
  1346-check-if-n-and-its-double-exist/NOTES.md
  1346-check-if-n-and-its-double-exist/README.md
  1436-destination-city/1436-destination-city.py
  1436-destination-city/NOTES.md
  1436-destination-city/README.md
  1656-design-an-ordered-stream/1656-design-an-ordered-stream.py
  1656-design-an-ordered-stream/NOTES.md
  1656-design-an-ordered-stream/README.md
  1814-count-nice-pairs-in-an-array/1814-count-nice-pairs-in-an-array.py
  1814-count-nice-pairs-in-an-array/NOTES.md
  1814-count-nice-pairs-in-an-array/README.md
  2099-find-subsequence-of-length-k-with-the-largest-sum/2099-find-subsequence-of-length-k-with-the-largest-sum.py
  2099-find-subsequence-of-length-k-with-the-largest-sum/NOTES.md
  2099-find-subsequence-of-length-k-with-the-largest-sum/README.md
  2341-maximum-number-of-pairs-in-array/2341-maximum-number-of-pairs-in-array.py
  2341-maximum-number-of-pairs-in-array/NOTES.md
  2341-maximum-number-of-pairs-in-array/README.md
  2442-count-number-of-distinct-integers-after-reverse-operations/2442-count-number-of-distinct-integers-after-reverse-operations.py
  2442-count-number-of-distinct-integers-after-reverse-operations/NOTES.md
  2442-count-number-of-distinct-integers-after-reverse-operations/README.md
Labels: 🎉 All pass

#137 Day 25
  0501-find-mode-in-binary-search-tree/0501-find-mode-in-binary-search-tree.java
  0501-find-mode-in-binary-search-tree/NOTES.md
  0501-find-mode-in-binary-search-tree/README.md
  0543-diameter-of-binary-tree/0543-diameter-of-binary-tree.java
  0543-diameter-of-binary-tree/NOTES.md
  0543-diameter-of-binary-tree/README.md
  1022-sum-of-root-to-leaf-binary-numbers/1022-sum-of-root-to-leaf-binary-numbers.java
  1022-sum-of-root-to-leaf-binary-numbers/NOTES.md
  1022-sum-of-root-to-leaf-binary-numbers/README.md
Labels: 🎉 All pass

#136 Day 25
  0501-find-mode-in-binary-search-tree/0501-find-mode-in-binary-search-tree.kt
  0501-find-mode-in-binary-search-tree/NOTES.md
  0501-find-mode-in-binary-search-tree/README.md
  0543-diameter-of-binary-tree/NOTES.md
  0543-diameter-of-binary-tree/README.md
  1022-sum-of-root-to-leaf-binary-numbers/NOTES.md
  1022-sum-of-root-to-leaf-binary-numbers/README.md
Labels: 🎉 All pass

#138 day 25
  0501-find-mode-in-binary-search-tree/0501-find-mode-in-binary-search-tree.kt
  0501-find-mode-in-binary-search-tree/NOTES.md
  0501-find-mode-in-binary-search-tree/README.md
  0543-diameter-of-binary-tree/0543-diameter-of-binary-tree.kt
  0543-diameter-of-binary-tree/NOTES.md
  0543-diameter-of-binary-tree/README.md
  1022-sum-of-root-to-leaf-binary-numbers/1022-sum-of-root-to-leaf-binary-numbers.kt
  1022-sum-of-root-to-leaf-binary-numbers/NOTES.md
  1022-sum-of-root-to-leaf-binary-numbers/README.md
Labels: 🎉 All pass

#140 day 26
  0404-sum-of-left-leaves/NOTES.md
  0404-sum-of-left-leaves/README.md
  0590-n-ary-tree-postorder-traversal/NOTES.md
  0590-n-ary-tree-postorder-traversal/README.md
  0606-construct-string-from-binary-tree/0606-construct-string-from-binary-tree.kt
  0606-construct-string-from-binary-tree/NOTES.md
  0606-construct-string-from-binary-tree/README.md
Labels: 🎉 All pass

#141 Day 26
  0404-sum-of-left-leaves/0404-sum-of-left-leaves.java
  0404-sum-of-left-leaves/NOTES.md
  0404-sum-of-left-leaves/README.md
  0590-n-ary-tree-postorder-traversal/0590-n-ary-tree-postorder-traversal.java
  0590-n-ary-tree-postorder-traversal/NOTES.md
  0590-n-ary-tree-postorder-traversal/README.md
  1684-count-the-number-of-consistent-strings/1684-count-the-number-of-consistent-strings.java
  1971-find-if-path-exists-in-graph/1971-find-if-path-exists-in-graph.java
  1971-find-if-path-exists-in-graph/NOTES.md
  1971-find-if-path-exists-in-graph/README.md
Labels: 🎉 All pass

#145 day 26
  0404-sum-of-left-leaves/NOTES.md
  0404-sum-of-left-leaves/README.md
  0590-n-ary-tree-postorder-traversal/0590-n-ary-tree-postorder-traversal.kt
  0590-n-ary-tree-postorder-traversal/NOTES.md
  0590-n-ary-tree-postorder-traversal/README.md
  0606-construct-string-from-binary-tree/0606-construct-string-from-binary-tree.kt
  0606-construct-string-from-binary-tree/NOTES.md
  0606-construct-string-from-binary-tree/README.md
Labels: 🎉 All pass

#146 day 27
  0653-two-sum-iv-input-is-a-bst/0653-two-sum-iv-input-is-a-bst.kt
  0653-two-sum-iv-input-is-a-bst/NOTES.md
  0653-two-sum-iv-input-is-a-bst/README.md
  1302-deepest-leaves-sum/1302-deepest-leaves-sum.kt
  1302-deepest-leaves-sum/NOTES.md
  1302-deepest-leaves-sum/README.md
Labels: 🎉 All pass

#147 day 27 & day 28
  0530-minimum-absolute-difference-in-bst/NOTES.md
  0653-two-sum-iv-input-is-a-bst/NOTES.md
  0653-two-sum-iv-input-is-a-bst/README.md
  0671-second-minimum-node-in-a-binary-tree/NOTES.md
  0671-second-minimum-node-in-a-binary-tree/README.md
  0783-minimum-distance-between-bst-nodes/NOTES.md
  0783-minimum-distance-between-bst-nodes/README.md
  1302-deepest-leaves-sum/NOTES.md
  1302-deepest-leaves-sum/README.md
Labels: 🎉 All pass

#151 Day 27 & 28
  0196-delete-duplicate-emails/0196-delete-duplicate-emails.sql
  0196-delete-duplicate-emails/NOTES.md
  0196-delete-duplicate-emails/README.md
  0653-two-sum-iv-input-is-a-bst/0653-two-sum-iv-input-is-a-bst.java
  0653-two-sum-iv-input-is-a-bst/NOTES.md
  0653-two-sum-iv-input-is-a-bst/README.md
  0671-second-minimum-node-in-a-binary-tree/0671-second-minimum-node-in-a-binary-tree.java
  0671-second-minimum-node-in-a-binary-tree/NOTES.md
  0671-second-minimum-node-in-a-binary-tree/README.md
  0783-minimum-distance-between-bst-nodes/0783-minimum-distance-between-bst-nodes.java
  0783-minimum-distance-between-bst-nodes/NOTES.md
  0783-minimum-distance-between-bst-nodes/README.md
  1302-deepest-leaves-sum/1302-deepest-leaves-sum.java
  1302-deepest-leaves-sum/NOTES.md
  1302-deepest-leaves-sum/README.md
Labels: 🎉 All pass

#153 day 28
  0530-minimum-absolute-difference-in-bst/0530-minimum-absolute-difference-in-bst.kt
  0530-minimum-absolute-difference-in-bst/NOTES.md
  0530-minimum-absolute-difference-in-bst/README.md
  0671-second-minimum-node-in-a-binary-tree/0671-second-minimum-node-in-a-binary-tree.kt
  0671-second-minimum-node-in-a-binary-tree/NOTES.md
  0671-second-minimum-node-in-a-binary-tree/README.md
  0783-minimum-distance-between-bst-nodes/0783-minimum-distance-between-bst-nodes.kt
  0783-minimum-distance-between-bst-nodes/NOTES.md
  0783-minimum-distance-between-bst-nodes/README.md
Labels: 🎉 All pass

#155 Day 14
  0303-range-sum-query-immutable/0303-range-sum-query-immutable.java
  0303-range-sum-query-immutable/NOTES.md
  0303-range-sum-query-immutable/README.md
  1122-relative-sort-array/1122-relative-sort-array.java
  1122-relative-sort-array/NOTES.md
  1122-relative-sort-array/README.md
  1158-market-analysis-i/1158-market-analysis-i.sql
  1158-market-analysis-i/NOTES.md
  1158-market-analysis-i/README.md
  1979-find-greatest-common-divisor-of-array/1979-find-greatest-common-divisor-of-array.java
  1979-find-greatest-common-divisor-of-array/NOTES.md
  1979-find-greatest-common-divisor-of-array/README.md
Labels: 🎉 All pass

#156 day 29
  0455-assign-cookies/0455-assign-cookies.kt
  0455-assign-cookies/NOTES.md
  0455-assign-cookies/README.md
  1221-split-a-string-in-balanced-strings/1221-split-a-string-in-balanced-strings.kt
  1221-split-a-string-in-balanced-strings/NOTES.md
  1221-split-a-string-in-balanced-strings/README.md
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/2160-minimum-sum-of-four-digit-number-after-splitting-digits.kt
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/NOTES.md
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/README.md
Labels: 🎉 All pass

#154 Day 29 & 30
  0455-assign-cookies/0455-assign-cookies.java
  0455-assign-cookies/NOTES.md
  0455-assign-cookies/README.md
  1221-split-a-string-in-balanced-strings/1221-split-a-string-in-balanced-strings.java
  1221-split-a-string-in-balanced-strings/NOTES.md
  1221-split-a-string-in-balanced-strings/README.md
  1323-maximum-69-number/NOTES.md
  1323-maximum-69-number/README.md
  1827-minimum-operations-to-make-the-array-increasing/1827-minimum-operations-to-make-the-array-increasing.java
  1827-minimum-operations-to-make-the-array-increasing/NOTES.md
  1827-minimum-operations-to-make-the-array-increasing/README.md
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/2160-minimum-sum-of-four-digit-number-after-splitting-digits.js
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/NOTES.md
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/README.md
  2389-longest-subsequence-with-limited-sum/2389-longest-subsequence-with-limited-sum.js
  2389-longest-subsequence-with-limited-sum/NOTES.md
  2389-longest-subsequence-with-limited-sum/README.md
Labels: 🎉 All pass

#158 day 30
  1323-maximum-69-number/1323-maximum-69-number.kt
  1323-maximum-69-number/NOTES.md
  1323-maximum-69-number/README.md
  1827-minimum-operations-to-make-the-array-increasing/1827-minimum-operations-to-make-the-array-increasing.kt
  1827-minimum-operations-to-make-the-array-increasing/NOTES.md
  1827-minimum-operations-to-make-the-array-increasing/README.md
  2389-longest-subsequence-with-limited-sum/2389-longest-subsequence-with-limited-sum.kt
  2389-longest-subsequence-with-limited-sum/NOTES.md
  2389-longest-subsequence-with-limited-sum/README.md
Labels: 🎉 All pass

#162 Day 31 & 32
  0942-di-string-match/0942-di-string-match.java
  0942-di-string-match/NOTES.md
  0942-di-string-match/README.md
  1217-minimum-cost-to-move-chips-to-the-same-position/1217-minimum-cost-to-move-chips-to-the-same-position.java
  1217-minimum-cost-to-move-chips-to-the-same-position/NOTES.md
  1217-minimum-cost-to-move-chips-to-the-same-position/README.md
  1403-minimum-subsequence-in-non-increasing-order/1403-minimum-subsequence-in-non-increasing-order.java
  1403-minimum-subsequence-in-non-increasing-order/NOTES.md
  1403-minimum-subsequence-in-non-increasing-order/README.md
  1710-maximum-units-on-a-truck/1710-maximum-units-on-a-truck.js
  1710-maximum-units-on-a-truck/NOTES.md
  1710-maximum-units-on-a-truck/README.md
  1974-minimum-time-to-type-word-using-special-typewriter/1974-minimum-time-to-type-word-using-special-typewriter.java
  1974-minimum-time-to-type-word-using-special-typewriter/NOTES.md
  1974-minimum-time-to-type-word-using-special-typewriter/README.md
Labels: 🎉 All pass

#161 Day 29 & 30
  0455-assign-cookies/NOTES.md
  0455-assign-cookies/README.md
  1221-split-a-string-in-balanced-strings/NOTES.md
  1221-split-a-string-in-balanced-strings/README.md
  1323-maximum-69-number/NOTES.md
  1323-maximum-69-number/README.md
  1827-minimum-operations-to-make-the-array-increasing/1827-minimum-operations-to-make-the-array-increasing.kt
  1827-minimum-operations-to-make-the-array-increasing/NOTES.md
  1827-minimum-operations-to-make-the-array-increasing/README.md
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/2160-minimum-sum-of-four-digit-number-after-splitting-digits.kt
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/NOTES.md
  2160-minimum-sum-of-four-digit-number-after-splitting-digits/README.md
  2389-longest-subsequence-with-limited-sum/NOTES.md
  2389-longest-subsequence-with-limited-sum/README.md
Labels: 🎉 All pass
