Repository I-JUNNYLAND-I/algorithm, pull requests merged in 2023-07, with the labels that each got.

#304 [W1] - day 1
  0017-letter-combinations-of-a-phone-number/0017-letter-combinations-of-a-phone-number.kt
  0017-letter-combinations-of-a-phone-number/NOTES.md
  0017-letter-combinations-of-a-phone-number/README.md
  0087-scramble-string/0087-scramble-string.java
  0087-scramble-string/NOTES.md
  0087-scramble-string/README.md
  0263-ugly-number/0263-ugly-number.kt
  0263-ugly-number/NOTES.md
  0263-ugly-number/README.md
  2439-minimize-maximum-of-array/2439-minimize-maximum-of-array.java
  2439-minimize-maximum-of-array/NOTES.md
  2439-minimize-maximum-of-array/README.md
  README.md
Labels: 🎉 All pass

#306 [W1] - day 1
  0011-container-with-most-water/README.md
  0017-letter-combinations-of-a-phone-number/0017-letter-combinations-of-a-phone-number.kt
  0017-letter-combinations-of-a-phone-number/NOTES.md
  0017-letter-combinations-of-a-phone-number/README.md
  0263-ugly-number/NOTES.md
  0263-ugly-number/README.md
  0577-employee-bonus/0577-employee-bonus.sql
  0577-employee-bonus/NOTES.md
  0577-employee-bonus/README.md
  백준/Silver/2606. 바이러스/README.md
  백준/Silver/2606. 바이러스/바이러스.kt
Labels: 🎉 All pass

#305 [W1] - day 1
  0011-container-with-most-water/0011-container-with-most-water.kt
  0011-container-with-most-water/NOTES.md
  0011-container-with-most-water/README.md
  0017-letter-combinations-of-a-phone-number/0017-letter-combinations-of-a-phone-number.kt
  0017-letter-combinations-of-a-phone-number/NOTES.md
  0017-letter-combinations-of-a-phone-number/README.md
  0263-ugly-number/0263-ugly-number.kt
  0263-ugly-number/NOTES.md
  0263-ugly-number/README.md
  0577-employee-bonus/0577-employee-bonus.sql
  0577-employee-bonus/NOTES.md
  0577-employee-bonus/README.md
Labels: 🎉 All pass

#307 [W1] - day1
  0011-container-with-most-water/0011-container-with-most-water.java
  0011-container-with-most-water/NOTES.md
  0011-container-with-most-water/README.md
  0017-letter-combinations-of-a-phone-number/0017-letter-combinations-of-a-phone-number.java
  0017-letter-combinations-of-a-phone-number/NOTES.md
  0017-letter-combinations-of-a-phone-number/README.md
  0263-ugly-number/0263-ugly-number.java
  0263-ugly-number/NOTES.md
  0263-ugly-number/README.md
  0577-employee-bonus/0577-employee-bonus.sql
  0577-employee-bonus/NOTES.md
  0577-employee-bonus/README.md
  백준/Bronze/27310. ：chino＿shock：/README.md
  백준/Bronze/27310. ：chino＿shock：/：chino＿shock：.py
  프로그래머스/lv3/12938. 최고의 집합/README.md
  프로그래머스/lv3/12938. 최고의 집합/최고의 집합.java
  프로그래머스/lv3/42893. 매칭 점수/README.md
  프로그래머스/lv3/42893. 매칭 점수/매칭 점수.java
  프로그래머스/unrated/154540. 무인도 여행/README.md
  프로그래머스/unrated/154540. 무인도 여행/무인도 여행.java
Labels: 🎉 All pass

#309 [W1] - day 2
  0535-encode-and-decode-tinyurl/0535-encode-and-decode-tinyurl.kt
  0535-encode-and-decode-tinyurl/NOTES.md
  0535-encode-and-decode-tinyurl/README.md
  0570-managers-with-at-least-5-direct-reports/0570-managers-with-at-least-5-direct-reports.sql
  0570-managers-with-at-least-5-direct-reports/NOTES.md
  0570-managers-with-at-least-5-direct-reports/README.md
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/1769-minimum-number-of-operations-to-move-all-balls-to-each-box.kt
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/NOTES.md
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/README.md
  2391-minimum-amount-of-time-to-collect-garbage/2391-minimum-amount-of-time-to-collect-garbage.kt
  2391-minimum-amount-of-time-to-collect-garbage/NOTES.md
  2391-minimum-amount-of-time-to-collect-garbage/README.md
Labels: 🎉 All pass

#310 [W1] - day 2
  .idea/.gitignore
  .idea/git_toolbox_prj.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/libraries/KotlinJavaRuntime.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/StudyLand.iml
  .idea/shelf/Uncommitted_changes_before_Update_at_2023-07-25__10_32__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Update_at_2023-07-25__10_46__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Update_at_2023-07-25_오전_10_32_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Update_at_2023-07-25_오전_10_46_[Changes]/shelved.patch
  .idea/vcs.xml
  .idea/workspace.xml
  0009-palindrome-number/0009-palindrome-number.kt
  0009-palindrome-number/NOTES.md
  0009-palindrome-number/README.md
  0535-encode-and-decode-tinyurl/0535-encode-and-decode-tinyurl.kt
  0535-encode-and-decode-tinyurl/NOTES.md
  0535-encode-and-decode-tinyurl/README.md
  0570-managers-with-at-least-5-direct-reports/0570-managers-with-at-least-5-direct-reports.sql
  0570-managers-with-at-least-5-direct-reports/NOTES.md
  0570-managers-with-at-least-5-direct-reports/README.md
  0852-peak-index-in-a-mountain-array/0852-peak-index-in-a-mountain-array.kt
  0852-peak-index-in-a-mountain-array/NOTES.md
  0852-peak-index-in-a-mountain-array/README.md
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/1769-minimum-number-of-operations-to-move-all-balls-to-each-box.kt
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/NOTES.md
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/README.md
  2391-minimum-amount-of-time-to-collect-garbage/2391-minimum-amount-of-time-to-collect-garbage.kt
  2391-minimum-amount-of-time-to-collect-garbage/NOTES.md
  2391-minimum-amount-of-time-to-collect-garbage/README.md
  StudyLand.iml
  out/production/0-Solution/META-INF/0-Solution.kotlin_module
  out/production/0-Solution/com/quid/codes/PalindromeNumber.class
  out/production/0-Solution/com/quid/codes/Solution.class
  out/production/0-Solution/com/quid/codes/SolutionKt.class
  out/production/0-Solution/com/quid/codes/history/PalindromeNumber.class
Labels: 🎉 All pass

#314 [W1] - day 2
  0535-encode-and-decode-tinyurl/0535-encode-and-decode-tinyurl.kt
  0535-encode-and-decode-tinyurl/NOTES.md
  0535-encode-and-decode-tinyurl/README.md
  0570-managers-with-at-least-5-direct-reports/0570-managers-with-at-least-5-direct-reports.sql
  0570-managers-with-at-least-5-direct-reports/NOTES.md
  0570-managers-with-at-least-5-direct-reports/README.md
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/1769-minimum-number-of-operations-to-move-all-balls-to-each-box.kt
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/NOTES.md
  1769-minimum-number-of-operations-to-move-all-balls-to-each-box/README.md
  2391-minimum-amount-of-time-to-collect-garbage/2391-minimum-amount-of-time-to-collect-garbage.kt
  2391-minimum-amount-of-time-to-collect-garbage/NOTES.md
  2391-minimum-amount-of-time-to-collect-garbage/README.md
Labels: 🎉 All pass

#312 [W1] - day 3
  0071-simplify-path/0071-simplify-path.kt
  0071-simplify-path/NOTES.md
  0071-simplify-path/README.md
  0072-edit-distance/0072-edit-distance.kt
  0072-edit-distance/NOTES.md
  0072-edit-distance/README.md
  0093-restore-ip-addresses/0093-restore-ip-addresses.kt
  0093-restore-ip-addresses/NOTES.md
  0093-restore-ip-addresses/README.md
  0118-pascals-triangle/0118-pascals-triangle.kt
  0118-pascals-triangle/NOTES.md
  0118-pascals-triangle/README.md
  1378-replace-employee-id-with-the-unique-identifier/1378-replace-employee-id-with-the-unique-identifier.sql
  1378-replace-employee-id-with-the-unique-identifier/NOTES.md
  1378-replace-employee-id-with-the-unique-identifier/README.md
Labels: 👻 miss algorithm

#313 [W1] - day 3
  0005-longest-palindromic-substring/0005-longest-palindromic-substring.kt
  0005-longest-palindromic-substring/NOTES.md
  0005-longest-palindromic-substring/README.md
  0071-simplify-path/0071-simplify-path.kt
  0071-simplify-path/NOTES.md
  0071-simplify-path/README.md
  0093-restore-ip-addresses/0093-restore-ip-addresses.kt
  0093-restore-ip-addresses/NOTES.md
  0093-restore-ip-addresses/README.md
  0209-minimum-size-subarray-sum/0209-minimum-size-subarray-sum.kt
  0209-minimum-size-subarray-sum/NOTES.md
  0209-minimum-size-subarray-sum/README.md
  1378-replace-employee-id-with-the-unique-identifier/1378-replace-employee-id-with-the-unique-identifier.sql
  1378-replace-employee-id-with-the-unique-identifier/NOTES.md
  1378-replace-employee-id-with-the-unique-identifier/README.md
Labels: 😥 hitted

#315 [W1] - day 3
  0071-simplify-path/0071-simplify-path.kt
  0071-simplify-path/NOTES.md
  0071-simplify-path/README.md
  0072-edit-distance/0072-edit-distance.kt
  0072-edit-distance/NOTES.md
  0072-edit-distance/README.md
  0093-restore-ip-addresses/0093-restore-ip-addresses.kt
  0093-restore-ip-addresses/NOTES.md
  0093-restore-ip-addresses/README.md
Labels: 👻 miss case

#320 [W1] - day 4
  1812-determine-color-of-a-chessboard-square/1812-determine-color-of-a-chessboard-square.kt
  1812-determine-color-of-a-chessboard-square/NOTES.md
  1812-determine-color-of-a-chessboard-square/README.md
  2125-number-of-laser-beams-in-a-bank/2125-number-of-laser-beams-in-a-bank.kt
  2125-number-of-laser-beams-in-a-bank/NOTES.md
  2125-number-of-laser-beams-in-a-bank/README.md
  2405-optimal-partition-of-string/2405-optimal-partition-of-string.kt
  2405-optimal-partition-of-string/NOTES.md
  2405-optimal-partition-of-string/README.md
Labels: 🎉 All pass

#321 [W1] - day 4 & [W1] - day 5
  0657-robot-return-to-origin/0657-robot-return-to-origin.kt
  0657-robot-return-to-origin/NOTES.md
  0657-robot-return-to-origin/README.md
  1061-lexicographically-smallest-equivalent-string/NOTES.md
  1061-lexicographically-smallest-equivalent-string/README.md
  1332-remove-palindromic-subsequences/NOTES.md
  1332-remove-palindromic-subsequences/README.md
  1396-design-underground-system/1396-design-underground-system.kt
  1396-design-underground-system/NOTES.md
  1396-design-underground-system/README.md
  1812-determine-color-of-a-chessboard-square/NOTES.md
  1812-determine-color-of-a-chessboard-square/README.md
  2125-number-of-laser-beams-in-a-bank/2125-number-of-laser-beams-in-a-bank.kt
  2125-number-of-laser-beams-in-a-bank/NOTES.md
  2125-number-of-laser-beams-in-a-bank/README.md
  2405-optimal-partition-of-string/2405-optimal-partition-of-string.kt
  2405-optimal-partition-of-string/NOTES.md
  2405-optimal-partition-of-string/README.md
Labels: 🎉 All pass, 😥 hitted

#323 [W1] - day 5
  1332-remove-palindromic-subsequences/1332-remove-palindromic-subsequences.kt
  1332-remove-palindromic-subsequences/NOTES.md
  1332-remove-palindromic-subsequences/README.md
Labels: 🎉 All pass

#322 [W1] - day 4
  1812-determine-color-of-a-chessboard-square/NOTES.md
  1812-determine-color-of-a-chessboard-square/README.md
  2405-optimal-partition-of-string/2405-optimal-partition-of-string.kt
  2405-optimal-partition-of-string/NOTES.md
  2405-optimal-partition-of-string/README.md
Labels: 🎉 All pass
